### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by brunobcfum** [iot-chalmers/wireless-paxos#1]
Hi!  Would you mind stating the requirements for OS and toolchain?

I managed to compile the code for the application, but can't run cooja.
I can run cooja from the official contiki rep (https://github.com/contiki-os/contiki) tho.

I tried in Ubuntu 14 and Ubuntu 18, with Openjdk (7,8 and 11) and IBM's Java.

Which version of OS and Java SDK do you use to run?

Some errors when I run "ant run" on  cooja folder:
```
compile:
    [javac] Compiling 78 source files to /home/bruno/wireless-paxos/tools/cooja/apps/mspsim/build
    [javac] /home/bruno/wireless-paxos/tools/cooja/apps/mspsim/src/org/contikios/cooja/mspmote/Wsn430Mote.java:40: error: cannot find symbol
    [javac] import se.sics.mspsim.platform.sky.WSN430Node;
    [javac]                                   ^
    [javac]   symbol:   class WSN430Node
```

**Comment by valpoi** [comment]
Hi,

It seems that the cooja version included does not work, I have pushed a new version that should compile and run. I tested it on a MacOS 10.15, Java version 8. The compiled sky image should also work on the current Cooja version in the official Contiki (and Contiki-NG) repositories.

Please note that when you create a new simulation in Cooja, you need to select the Multi-path Ray-tracer Medium (MRM) environment. This is the only environment correctly simulating concurrent transmissions in Cooja.
Don't hesitate if you have more questions!

**Comment by brunobcfum** [comment]
Thanks! It worked.
